### ISSUE TITLE
Test WooCommerce 4.4.1 and Woo-Viet 1.4.5

### ISSUE THREAD

**Issue by htdat** [htdat/woo-viet#73]
### OnePay domestic module
 
- [x] Checked this doc https://mtf.onepay.vn/developer/resource/documents/docx/introduction_merchant_integration_local.pdf - last update 17th April, 2019 - ver 2.1
- [x] `queryDR` response - works! 
- [x] `return` response - works!
- [x] It's a bit confusing that `vpc_Version = 2` in WooViet_OnePay_Domestic::get_pay_url() while `vpc_Version = 1` for queryDR. However, that's correct with their doc above as well as the example code in https://mtf.onepay.vn/developer/?page=modul_noidia_php

- [x] Everything is still working without changing anything.

### Other features 

- [x] Add provinces for Vietnam
- [x] Add districts 
- [x] Change VND symbol 
- [x] Convert `000` to K
- [x] Suport VND for PayPal Standard
- [ ] Support VND for PayPal Checkout

**Comment by htdat** [comment]
Error in log when testing ` Support VND for PayPal Checkout`

```
2020-09-02T13:35:45+00:00 CRITICAL Uncaught Error: Call to a member function get_currency() on null in /srv/htdocs/wp-content/plugins/woo-viet-add-onepay-intl/inc/class-wooviet-vnd-paypal-express-checkout.php:70
Stack trace:
#0 /wordpress/core/5.5.1/wp-includes/class-wp-hook.php(287): WooViet_VND_PayPal_Express_Checkout->ppec_match_currency_order(Array)
#1 /wordpress/core/5.5.1/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#2 /wordpress/core/5.5.1/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /srv/htdocs/wp-content/plugins/woocommerce-gateway-paypal-express-checkout/includes/class-wc-gateway-ppec-ipn-handler.php(34): do_action('woocommerce_pay...', Array)
#4 /wordpress/core/5.5.1/wp-includes/class-wp-hook.php(287): WC_Gateway_PPEC_IPN_Handler->check_request('')
#5 /wordpress/core/5.5.1/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#6 /wordpress/core/5.5.1/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#7 /srv/htdocs/wp-content/plugins/woocommerce/includes/class-wc-api.php(148): do_action('woocommerce_api...')
#8 /wordpress/core/5.5.1/wp-includes/class-wp-hook.php(287): WC_API->handle_api_requests(Object(WP))
#9 /wordpress/core/5.5.1/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array)
#10 /wordpress/core/5.5.1/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
#11 /wordpress/core/5.5.1/wp-includes/class-wp.php(388): do_action_ref_array('parse_request', Array)
#12 /wordpress/core/5.5.1/wp-includes/class-wp.php(745): WP->parse_request('')
#13 /wordpress/core/5.5.1/wp-includes/functions.php(1285): WP->main('')
#14 /wordpress/core/5.5.1/wp-blog-header.php(16): wp()
#15 /wordpress/core/5.5.1/index.php(17): require('/wordpress/core...')
#16 {main}
  thrown in /srv/htdocs/wp-content/plugins/woo-viet-add-onepay-intl/inc/class-wooviet-vnd-paypal-express-checkout.php on line 70

```

**Comment by htdat** [comment]
# Support VND for PayPal Checkout - after the fix above 

When trying to check out on the front-end (the checkout page or anywhere with PayPal checkout button). This is the error on the browser console. 

> Error: Expected currency from order api call to be VND, got USD. Please ensure you are passing currency=USD to the sdk url. https://developer.paypal.com/docs/checkout/reference/customize-sdk/

## Debug 

The plugin is trying to load this JS link - notice `currency=VND`

> <script data-namespace="paypal_sdk" src='https://www.paypal.com/sdk/js?client-id=sb&#038;merchant-id=AFVXYG3YTJA4A&#038;intent=capture&#038;locale=en_US&#038;components=buttons,funding-eligibility&#038;commit=false&#038;currency=VND' id='paypal-checkout-sdk-js'>

This is handled here 

https://github.com/woocommerce/woocommerce-gateway-paypal-express-checkout/blob/f1f16de178cbf1d529deeaf574a52aca82a6e093/includes/class-wc-gateway-ppec-cart-handler.php#L553-L556

### Temp fix 

Run this filter 

```php
add_filter ('woocommerce_paypal_express_checkout_sdk_script_args', function( $script_args ) {
	$script_args['currency'] = 'USD';  
	return $script_args; 
}); 
```

### Permanent fix 

Replace `USD` by the setting in Woo Viet.
